[features]
seeds = false
skip-lint = false
[programs.localnet]
cega = "CAxcPk6uf5a92YswtUVB94LCWD3sUJinpYJ8qLdpPCZA"

[programs.devnet]
cega = "CAxcPk6uf5a92YswtUVB94LCWD3sUJinpYJ8qLdpPCZA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ahzam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
